yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Модель, описывающая группы пользователей."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return str(self.title)


class Post(models.Model):
    """Модель, описывающая посты пользователей."""
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self) -> str:
        return str(self.text[:15])

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    """Модель, описывающая комментраии пользователей."""
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        'Дата написания',
        auto_now_add=True,
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )

    def __str__(self) -> str:
        return str(self.text[:15])

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    """Модель, описывающая подсписки пользователей
    друг на друга.
    """
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment
from django.forms.widgets import Textarea, Select


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    widgets = {
        'text': Textarea,
        'group': Select,
    }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    widgets = {
        'text': Textarea,
    }

yatube/posts/views.py
from typing import Dict

from django.core.paginator import Paginator
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow

POSTS_ON_INDEX_PAGE = 10
POSTS_ON_GROUP_POSTS_PAGE = 10
POSTS_ON_PROFILE_PAGE = 10

User = get_user_model()


def index(request: HttpRequest) -> HttpResponse:
    """"Обработка запросов к главной странице."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_ON_INDEX_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title: str = "Последние обновления на сайте"
    context: Dict = {
        'title': title,
        'page_obj': page_obj,
        'index': True,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: HttpRequest, slug) -> HttpResponse:
    """Обработка запросов к странице конкретного сообщества."""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, POSTS_ON_GROUP_POSTS_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title: str = f'Записи сообщества {group.title}'
    context: Dict = {
        'title': title,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """Отображение всех постов конкретного пользователя."""
    if request.user.is_authenticated:
        follow = User.objects.get(username=username)
        following = (
            Follow.objects
            .filter(user=request.user, author=follow)
            .exists()
        )
    else:
        following = False
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    paginator = Paginator(post_list, POSTS_ON_PROFILE_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Отображение подробной информации по одному посту."""
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    number_of_posts = Post.objects.filter(author=author).count()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'number_of_posts': number_of_posts,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Создание нового поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        form.save()
        return redirect(f'/profile/{request.user}/')
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    """Редактирование существующего поста."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Добавление комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Страница с постами отслеживаемых людей."""
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, POSTS_ON_INDEX_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title: str = "Последние обновления на сайте"
    context: Dict = {
        'title': title,
        'page_obj': page_obj,
        'follow': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    follow = get_object_or_404(User, username=username)
    if follow != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=follow,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    follow = get_object_or_404(User, username=username)
    is_exist = (
        Follow.objects
        .filter(user=request.user, author=follow)
        .exists()
    )
    if is_exist:
        Follow.objects.filter(user=request.user, author=follow).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load  user_filters %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

{% block title %}
    {% if is_edit %}
        Редактировать запись
    {% else %}
        Добавить запись
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Новый пост
                </div>
                <div class="card-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field|addclass:'form-control' }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Автор: {{ post.author }}
                    <a href="{% url 'posts:profile' post.author %}">
                        все посты пользователя
                    </a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:'d E Y' }}
                </li>
            </ul>
            <p>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            </p>
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group != null %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <h1>Записи сообщества: {{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author %}">
                        все посты пользователя
                    </a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:'d E Y' }}
                </li>
            </ul>
            <p>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            </p>
            <p>
                {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if not forloop.last %}
            <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}
    {% cache 20 index_page page_obj.number %}
        {% for post in page_obj %}
            <article>
                <ul>
                    <li>
                        Автор: {{ post.author }}
                        <a href="{% url 'posts:profile' post.author %}">
                            все посты пользователя
                        </a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:'d E Y' }}
                    </li>
                </ul>
                <p>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                </p>
                <p>{{ post.text }}</p>
                <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
            </article>
            {% if post.group != null %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации:
                    {{ post.pub_date|date:'d E Y' }}
                </li>
                {% if post.group != null %}
                    <li class="list-group-item">
                    Группа:
                    {{ post.group }}
                    <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
                {% endif %}
                </li>
                <li class="list-group-item">
                    Автор:
                    {{ post.author }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора: <span>
                    {{ number_of_posts }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author %}">
                        Все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p>
                {{ post.text }}
            </p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
        {% if post.author == request.user %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                редактировать запись
            </a>
        {% endif %}
            {% include 'includes/comments.html' %}
        </article>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
    <div class="mb-5">
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ page_obj.object_list.count }} </h3>
        {% if following %}
            <a
                    class="btn btn-lg btn-light"
                    href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
            </a>
        {% else %}
            <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button">
                Подписаться
            </a>
        {% endif %}
    </div>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Дата публикации: {{ post.pub_date|date:'d E Y' }}
                </li>
            </ul>
            <p>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            </p>
            <p>
                {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group != null %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        <hr>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}